### PR TITLE
About us sponsors

### PR DESCRIPTION
**Pull request by AnnaLenaO**
With example logo & example js for link to a sponsor.

### CODE REVIEW

**Comment by AnnaLenaO** [comment]
> Might I suggest making the border radius like this on line 24 of ourSponsors.scss. "border-radius: 15px 15px 0 0;" So that it looks like this? image

Thank you for your suggestion. According to the wireframe in figma all four corners are rounded. Therefore the border-raidus is 15Px. Here is an image from figma to show what I mean: 
image

**Comment by EmilioSanchezLernia** [comment]
Fair enough I can respect it in that case 👍

**Review by EmilioSanchezLernia — APPROVED** [review]
Everything works as intended and looks good.
Great job!

**Review by Weeezzt — APPROVED** [review]
I can see that you've used BEM in the new html file and created a new scss file in the src map all according to our best practices, perfect. I can't find anything wrong with this. I saw Emilios suggestion which I could get behind but I think its best to follow the figma at least for now.

**Comment by AnnaLenaO** [comment]
Thank you both for your comments on this PR.

**Pull request merged**
