### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Kookiie88**
Added best practice rules to readme.md

### CODE REVIEW

**Review by Weeezzt — APPROVED** [review]
Nice! Good idea to have our rules in a README.

**Review by MatsJoh50 — APPROVED** [review]
Ah. How could we miss this :) superb!

**Review by EmilioSanchezLernia — APPROVED** [review]
Just like the teacher mentioned, it's good this is getting added even if a tiny bit late!

**Comment by AnnaLenaO** [comment]
Very nice summary of the project rules & best practices.

**Pull request merged**
