### PR TITLE
Added the news and events API

### PR DESCRIPTION
**Pull request by EmilioSanchezLernia**
Added a simple news and events API with 5 news and 5 events.
The content is written in Swedish but the API is in English.

### CODE REVIEW

**Review by Kookiie88 — CHANGES_REQUESTED** [review]
I've taken a look at the "API," and I'm feeling a bit puzzled. From what I gather, the date provided seems to be either the movie release date or the event date. If that's accurate, I'd like to suggest including the article's publication date as well. Thanks!

**Review by Weeezzt — COMMENTED** [review]
I've looked at the APIs, I feel like maybe it would be a good idea to ad a "published" key or something similar so that the value could be the date for when the "article" is published.

**Comment by EmilioSanchezLernia** [comment]
I have changed "date" to "published" as per Williams suggestion and I also made all dates singular as I agree it was confusing and didn't make sense. I hope it makes more sense now, appreciate the feedback guys! 👍

**Review by Kookiie88 — APPROVED** [review]

**Comment by Kookiie88** [comment]
I have reviewed and accepted the modifications. The publication date of the news post is now more apparent. Although it is set in the future, it's worth noting that this is a fictional page, so the actual date is not crucial.

**Review by Weeezzt — APPROVED** [review]
I've looked at the modifications and i think that its better now when theres "published" with the date it got published on the site. Approved

**Pull request merged**
