### PR TITLE
Build hamburger menu

### PR DESCRIPTION
**Pull request by Kookiie88**
I have successfully developed the hamburger menu in line with the stylistic preferences outlined in our Figma document. Additionally, I want to highlight that the header has now been optimized for a mobile-first approach, in accordance with contemporary design principles. 
Please refer to the images below:

Screenshot 2023-12-28 231155
Screenshot 2023-12-28 231202
Screenshot 2023-12-28 231207
Screenshot 2023-12-28 231211

Do note that when you take the header from the headerAndFooter.html you will need to add this class and add the script src in the head:
Screenshot 2023-12-28 231422
Screenshot 2023-12-28 231428

Also you will need to insert the href links to the pages when they have been created on line 18, 19, 20, 29, 30 and 31:

Screenshot 2023-12-28 231927
Screenshot 2023-12-28 231932

### CODE REVIEW

**Comment by Kookiie88** [comment]
I also added a additional breakpoint that i needed for the hamburger menu to look good in all different screen sizes:

$small: 480px;
$medium: 750px; <------ _Added this one_
$large: 998px;
$extraLarge: 1200px;

**Review by MatsJoh50 — APPROVED** [review]
Added comment on line 29 in main.scss

seems to work good!

**Comment by Kookiie88** [comment]
i added a template folder where i put the header and footer file and the template for the movie cards will also be there.

**Review by EmilioSanchezLernia — APPROVED** [review]
Everything looks correct and the documentation is very extensive and useful on the changes and implementation. Amazing job Alexander! 💯

**Pull request merged**
