### PR TITLE
Filmer hero

### PR DESCRIPTION
**Pull request by MatsJoh50**
Responsive hero section for Filmer.html

Generates a random poster from movies api with the title.

Should be able to add a filter function if we only want to see "popular" "upcoming" or "kids" ...

### CODE REVIEW

**Review by EmilioSanchezLernia — APPROVED** [review]
Works best in mobile view, but it looks nice and properly randomly loads different movies for the hero!

**Review by Weeezzt — COMMENTED** [review]
on thing that im a bit hesitant about is that the hero is 90vw, however the posters thats in the api are kind of in a standing perspective, might look a bit weird in a landscape perspective. All in all i think the code looks good.

**Review by AnnaLenaO — APPROVED** [review]
The responsiveness looks great! At small screens the filter bars and the title of the movie lies on top of the drop down menue. This might be solved when merged into main branch. If not it could be easily fixed after merge. Therefore I approve this PR due to the big queue (6/5) for PR and the near stop date we have for the project.

**Comment by Kookiie88** [comment]
Fixed the z-index problem that occured.

**Review by Kookiie88 — APPROVED** [review]
Everything looks correct and you have removed the added scss that you had for the footer.

**Pull request merged**
