### PR TITLE
Build header

### PR DESCRIPTION
**Pull request by Kookiie88**
I have successfully completed the header design for the desktop version. Additionally, I've implemented a maximum width constraint for the header to prevent it from endlessly stretching on exceptionally wide screens. The specified limit is set at 1200 pixels. Feel free to examine the outcomes in the images provided with this message.

Screenshot 2023-12-27 231047
Screenshot 2023-12-27 231055

### CODE REVIEW

**Review by Weeezzt — COMMENTED** [review]
I think its good that youve provided an alt for the img since its essential for accessibility. I like how you've used BEM like we talked about and how you've nested the selectors in SCSS. The desktop version looks great but i thought we said that we should do mobile-first. Other then that, great work!

**Comment by Kookiie88** [comment]
> I think its good that youve provided an alt for the img since its essential for accessibility. I like how you've used BEM like we talked about and how you've nested the selectors in SCSS. The desktop version looks great but i thought we said that we should do mobile-first. Other then that, great work!

I initially focused on the desktop version, and my next task involves developing the mobile hamburger menu. The hamburger menu is designated as the default display, with the desktop version of the header appearing on larger screens. Once both versions are created, I will implement the code to toggle between the menus. I chose to start with the desktop version due to the limited time I had available today, so I opted for the menu element that required less time. Converting it to a mobile-first design involves just a minor code adjustment. However, my plan for tomorrow is to concentrate on the hamburger menu and ensure it becomes the default menu in the code.

**Review by EmilioSanchezLernia — APPROVED** [review]
Includes all the relevant buttons and the logo. Just missing the hamburger menu and it will be fully complete! 👍

**Review by Weeezzt — APPROVED** [review]
I understand now why you did desktop first. I´ll approve the PR

**Pull request merged**
