### PR TITLE
Header footer links

### PR DESCRIPTION
**Pull request by Kookiie88**
Added the links and too the footer and the header and also included a link on the logo that brings you to index.html

### CODE REVIEW

**Comment by Weeezzt** [comment]
Everything worked fine for me except the logo link: 

Screenshot 2024-01-03 at 15 00 15

**Review by Weeezzt — APPROVED** [review]
All good

**Review by EmilioSanchezLernia — APPROVED** [review]
It's great you managed to fix the issues we talked about on Teams. 
Great job man, the fixes look good!

**Comment by Kookiie88** [comment]
This PR is directly linked to creating the header and footer it is just the addition of the links

**Pull request merged**
